apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: jupyter
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  serviceName: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: us.gcr.io/hazel-aria-174703/probcomp:0.4
        resources:
          limits:
            memory: 2000Mi
        ports:
        - name: http
          containerPort: 8888
        volumeMounts:
        - name: jupyter-data
          mountPath: /notebook
  volumeClaimTemplates:
  - metadata:
      name: jupyter-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
