apiVersion: v1
kind: Service
metadata:
  name: jupyter-axch
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: jupyter-axch
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jupyter-axch
  labels:
    app: jupyter-axch
spec:
  serviceName: jupyter-axch
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-axch
    spec:
      containers:
      - name: jupyter-axch
        image: us.gcr.io/hazel-aria-174703/probcomp:0.6
        resources:
          limits:
            memory: 2000Mi
        ports:
        - name: http
          containerPort: 8888
        volumeMounts:
        - name: jupyter-data-axch
          mountPath: /notebook
  volumeClaimTemplates:
  - metadata:
      name: jupyter-data-axch
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
