version: "3"
volumes:
  jupyter-data:
    driver: local

services:
  jupyter: &app_base
    build:
      context: docker/
      dockerfile: probcomp-scipy-notebook
    ports:
      - 8888:8888
    volumes:
      - jupyter-data:/home/jovyan/work:rw
